### PR TITLE
Rhel6 integration

### PR DESCRIPTION
**Pull request by joe-lawrence**

### CODE REVIEW

**Comment by joe-lawrence** [comment]
I can rebase if that makes the merge easier.  LMK.

**Comment by flaming-toast** [comment]
Ah, let me clean up and rebase my branch so that it's up to date with master, and then we can just pile our commits on top.

**Comment by flaming-toast** [comment]
Hm. I'm worried that some of the recent commits from master are incompatible with rhel6 (eg, new stacktrace stuff). I'll have to hold off updating this branch against upstream kpatch for now. For the meantime, could you rebase your branch against mine, and add your integration test commit on top? That way I can take your stuff immediately, and I'll have to do a proper rebase another time (as I'll need to re-test everything against rhel6)

**Comment by joe-lawrence** [comment]
I just did a ```git fetch flaming-toast``` + ```git rebase remotes/flaming-toast/kpatch-rhel6``` and then force pushed up to my repo.  It's still complaining about branch conflicts...  I think it's complaining because the PR wants to go to your master branch.

**Comment by joe-lawrence** [comment]
Okay, looks like I was able to modify the target base after the fact.  See how that looks now.

**Comment by flaming-toast** [comment]
This looks great! Thank you!! :-)

**Pull request merged**
